-- Elias AI / utility feature schema backup
-- Preserves the database tables used by conversational AI, memories,
-- summaries, reminders, AFK, Crunchyroll watch history, and channel modes.
-- This is a source backup; existing database data is not modified by this file.

create table if not exists public.channels (
  channel_id text primary key,
  guild_id text not null,
  mode text not null check (mode in ('main', 'semi', 'blocked')),
  updated_at timestamptz not null default now()
);

create index if not exists channels_guild_id_idx on public.channels(guild_id);

create table if not exists public.users (
  discord_id text primary key,
  username text not null,
  display_name text,
  updated_at timestamptz not null default now()
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  discord_id text not null,
  memory text not null,
  importance real not null default 0.5 check (importance >= 0 and importance <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists memories_user_idx on public.memories(guild_id, discord_id, updated_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  channel_id text not null,
  discord_id text not null,
  username text not null,
  content text not null,
  is_bot boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists messages_channel_idx on public.messages(guild_id, channel_id, created_at desc);

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  discord_id text not null,
  channel_id text not null,
  task text not null,
  due_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists reminders_due_idx on public.reminders(due_at);
create index if not exists reminders_user_idx on public.reminders(guild_id, discord_id, due_at);

create table if not exists public.afk_status (
  guild_id text not null,
  discord_id text not null,
  username text not null,
  display_name text not null,
  reason text,
  started_at timestamptz not null,
  mention_count integer not null default 0,
  pingers jsonb not null default '[]'::jsonb,
  primary key (guild_id, discord_id)
);

create index if not exists afk_guild_idx on public.afk_status(guild_id);

create table if not exists public.crunchyroll_last_watch (
  discord_id text primary key,
  anime_title text not null,
  episode_title text,
  season integer,
  episode integer,
  thumbnail_url text,
  watched_at timestamptz not null default now()
);
