-- Run once in the existing Elias Supabase project.
create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  discord_id text not null,
  channel_id text not null,
  task text not null,
  due_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists reminders_due_idx on public.reminders(due_at);
create index if not exists reminders_user_idx on public.reminders(guild_id, discord_id, due_at);
